# docker-compose.yml: # defines how to build and run both the client and server services together.
# here we are using it to run the image only
# Version of the Docker Compose file format. Using '3.8' is a common and stable choice.
version: '3.8'

# 'services' defines the containers for our application.
# Each service will be a separate container.
services:
  # This is the name of our server-side service
  server:
    # not needed files not on server to build
    # Using 'build' instead of 'image' because we have a Dockerfile ---
    # This tells Docker Compose to build the server's image using the Dockerfile
    # in the current directory (`.`), before starting the container.
    # build: .
    # 'image' gives a name and tag to the image that will be built.
    # We use 'latest' to indicate it's the most recent build.
    image: hibaanadani/docker-backend:22
    # using service database
    environment:
      # we're now using env variables from our CI/CD pipeline
      # The backend connects to 'mongodb_db' service name, not a URL
      # Inside the Docker network, services find each other by their name.
      - MONGODB_DATABASE_HOST=mongodb_db
      
    # 'ports' maps a port on the host machine to a port in the container.
    # The format is "HOST_PORT:CONTAINER_PORT".
    # This allows us to access the server from our local machine at http://localhost:9000.
    ports:
      - "9000:9000"
    # The 'depends_on' key ensures the server service will not start until
    # the database services are running and healthy.
    # now it also depends on n8n to be up and running
    depends_on:
      - mongodb_db
    # restart when a problem occurs in a container instead of shutting down
    restart: always

  # The MongoDB non-relational database service.
  mongodb_db:
    # Use the official MongoDB image from Docker Hub.
    image: mongo:latest
    # Environment variables for initial setup.
    environment:
      # Set the root user's username. This is for initial access.
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      # Set the root user's password.
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      # Create an initial database on startup.
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
      # The host variable is for a client (like your backend) to connect to the database,
      # not for the database itself to know its own address.
    # Persist data using a named volume.
    volumes:
      - mongodb_data:/data/db
    # Map the standard MongoDB port (27017) to the host.
    ports:
      - "27017:27017"
    # restart when a problem occurs in a container instead of shutting down
    restart: always

 
# 'volumes' are defined outside the services block.
# This creates a persistent storage space for our database data.
# The volume name is updated to match the MongoDB service.
volumes:
  # dbdata:
  mongodb_data: